version: "3"

services:
  nginx:
    build:
      context: config/nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    links:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - support.badgerherald.org-wordpress:/var/www/html
      - ./bin/wp-content:/var/www/html/wp-content/
      - ./${WORDPRESS_UPLOADS_DIR}:/var/www/html/wp-content/uploads
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: 10
    environment:
      DOMAIN: ${SITE_URL}

  wordpress:
    build:
      context: config/wordpress
    container_name: ${COMPOSE_PROJECT_NAME}-wordpress
    links:
      - redis
    depends_on:
      - mariadb
    expose:
      - 80
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: 10
    volumes:
      - support.badgerherald.org-wordpress:/var/www/html
      - ./${WORDPRESS_UPLOADS_DIR}:/var/www/html/wp-content/uploads
      - ./bin/stencil-stats.json:/srv/stencil-stats.json
      - ./bin/wp-content/themes:/var/www/html/wp-content/themes/
      - ./config/wordpress/wp-content/object-cache.php:/var/www/html/wp-content/object-cache.php
      - ./config/wordpress/php.ini:/usr/local/etc/php/conf.d/extra.ini
      - ./config/wordpress/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-my-extra.conf
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA:
        /* Domain */
        define('WP_HOME','https://${SITE_URL}');
        define('WP_SITEURL','https://${SITE_URL}');
        define('WP_CACHE',true);
        define('WP_MEMORY_LIMIT','128M');
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PASSWORD', '${REDIS_PASSWORD}' );
        define('WP_CACHE_KEY_SALT', '${SITE_URL}');
        define('DISABLE_WP_CRON', true);
        $$memcached_servers = array(
          'default' => array(
            'memcached:11211',
          )
        );

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    image: redis:6
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: 10
    ports:
      - "6379:6379"

volumes:
  support.badgerherald.org-wordpress:

networks:
  default:
    name: support.badgerherald.org-network
    external: true
