/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Post, Query, Single, Template, Theme } from "@webpress/core";
export namespace Components {
    interface Bhaa404 {
    }
    interface BhaaApp {
        "query": Template.Query;
        "theme": Theme;
    }
    interface BhaaExpandingCopy {
        "linkText": string;
        "post": Single;
    }
    interface BhaaFooter {
        "query": Template.Query;
        "theme": Theme;
    }
    interface BhaaGridReveal {
    }
    interface BhaaHeader {
        "query": Template.Query;
        "theme": Theme;
    }
    interface BhaaHeartHerald {
        "theme": Theme;
    }
    interface BhaaLoadingSpinner {
    }
    interface BhaaMain {
        "query": Query<Single>;
        "slug": String;
    }
    interface BhaaMainSection {
    }
    interface BhaaMenu {
        "theme": Theme;
    }
    interface BhaaPage {
        "query": Query<Post>;
    }
    interface BhaaPost {
        "query": Query<Post>;
    }
    interface BhaaPostBreadcrumbs {
        "post": Single;
    }
    interface BhaaQzip {
    }
    interface BhaaSticker {
    }
    interface BhaaUpdates {
        "query": Query<Single>;
    }
}
declare global {
    interface HTMLBhaa404Element extends Components.Bhaa404, HTMLStencilElement {
    }
    var HTMLBhaa404Element: {
        prototype: HTMLBhaa404Element;
        new (): HTMLBhaa404Element;
    };
    interface HTMLBhaaAppElement extends Components.BhaaApp, HTMLStencilElement {
    }
    var HTMLBhaaAppElement: {
        prototype: HTMLBhaaAppElement;
        new (): HTMLBhaaAppElement;
    };
    interface HTMLBhaaExpandingCopyElement extends Components.BhaaExpandingCopy, HTMLStencilElement {
    }
    var HTMLBhaaExpandingCopyElement: {
        prototype: HTMLBhaaExpandingCopyElement;
        new (): HTMLBhaaExpandingCopyElement;
    };
    interface HTMLBhaaFooterElement extends Components.BhaaFooter, HTMLStencilElement {
    }
    var HTMLBhaaFooterElement: {
        prototype: HTMLBhaaFooterElement;
        new (): HTMLBhaaFooterElement;
    };
    interface HTMLBhaaGridRevealElement extends Components.BhaaGridReveal, HTMLStencilElement {
    }
    var HTMLBhaaGridRevealElement: {
        prototype: HTMLBhaaGridRevealElement;
        new (): HTMLBhaaGridRevealElement;
    };
    interface HTMLBhaaHeaderElement extends Components.BhaaHeader, HTMLStencilElement {
    }
    var HTMLBhaaHeaderElement: {
        prototype: HTMLBhaaHeaderElement;
        new (): HTMLBhaaHeaderElement;
    };
    interface HTMLBhaaHeartHeraldElement extends Components.BhaaHeartHerald, HTMLStencilElement {
    }
    var HTMLBhaaHeartHeraldElement: {
        prototype: HTMLBhaaHeartHeraldElement;
        new (): HTMLBhaaHeartHeraldElement;
    };
    interface HTMLBhaaLoadingSpinnerElement extends Components.BhaaLoadingSpinner, HTMLStencilElement {
    }
    var HTMLBhaaLoadingSpinnerElement: {
        prototype: HTMLBhaaLoadingSpinnerElement;
        new (): HTMLBhaaLoadingSpinnerElement;
    };
    interface HTMLBhaaMainElement extends Components.BhaaMain, HTMLStencilElement {
    }
    var HTMLBhaaMainElement: {
        prototype: HTMLBhaaMainElement;
        new (): HTMLBhaaMainElement;
    };
    interface HTMLBhaaMainSectionElement extends Components.BhaaMainSection, HTMLStencilElement {
    }
    var HTMLBhaaMainSectionElement: {
        prototype: HTMLBhaaMainSectionElement;
        new (): HTMLBhaaMainSectionElement;
    };
    interface HTMLBhaaMenuElement extends Components.BhaaMenu, HTMLStencilElement {
    }
    var HTMLBhaaMenuElement: {
        prototype: HTMLBhaaMenuElement;
        new (): HTMLBhaaMenuElement;
    };
    interface HTMLBhaaPageElement extends Components.BhaaPage, HTMLStencilElement {
    }
    var HTMLBhaaPageElement: {
        prototype: HTMLBhaaPageElement;
        new (): HTMLBhaaPageElement;
    };
    interface HTMLBhaaPostElement extends Components.BhaaPost, HTMLStencilElement {
    }
    var HTMLBhaaPostElement: {
        prototype: HTMLBhaaPostElement;
        new (): HTMLBhaaPostElement;
    };
    interface HTMLBhaaPostBreadcrumbsElement extends Components.BhaaPostBreadcrumbs, HTMLStencilElement {
    }
    var HTMLBhaaPostBreadcrumbsElement: {
        prototype: HTMLBhaaPostBreadcrumbsElement;
        new (): HTMLBhaaPostBreadcrumbsElement;
    };
    interface HTMLBhaaQzipElement extends Components.BhaaQzip, HTMLStencilElement {
    }
    var HTMLBhaaQzipElement: {
        prototype: HTMLBhaaQzipElement;
        new (): HTMLBhaaQzipElement;
    };
    interface HTMLBhaaStickerElement extends Components.BhaaSticker, HTMLStencilElement {
    }
    var HTMLBhaaStickerElement: {
        prototype: HTMLBhaaStickerElement;
        new (): HTMLBhaaStickerElement;
    };
    interface HTMLBhaaUpdatesElement extends Components.BhaaUpdates, HTMLStencilElement {
    }
    var HTMLBhaaUpdatesElement: {
        prototype: HTMLBhaaUpdatesElement;
        new (): HTMLBhaaUpdatesElement;
    };
    interface HTMLElementTagNameMap {
        "bhaa-404": HTMLBhaa404Element;
        "bhaa-app": HTMLBhaaAppElement;
        "bhaa-expanding-copy": HTMLBhaaExpandingCopyElement;
        "bhaa-footer": HTMLBhaaFooterElement;
        "bhaa-grid-reveal": HTMLBhaaGridRevealElement;
        "bhaa-header": HTMLBhaaHeaderElement;
        "bhaa-heart-herald": HTMLBhaaHeartHeraldElement;
        "bhaa-loading-spinner": HTMLBhaaLoadingSpinnerElement;
        "bhaa-main": HTMLBhaaMainElement;
        "bhaa-main-section": HTMLBhaaMainSectionElement;
        "bhaa-menu": HTMLBhaaMenuElement;
        "bhaa-page": HTMLBhaaPageElement;
        "bhaa-post": HTMLBhaaPostElement;
        "bhaa-post-breadcrumbs": HTMLBhaaPostBreadcrumbsElement;
        "bhaa-qzip": HTMLBhaaQzipElement;
        "bhaa-sticker": HTMLBhaaStickerElement;
        "bhaa-updates": HTMLBhaaUpdatesElement;
    }
}
declare namespace LocalJSX {
    interface Bhaa404 {
    }
    interface BhaaApp {
        "query"?: Template.Query;
        "theme"?: Theme;
    }
    interface BhaaExpandingCopy {
        "linkText"?: string;
        "post"?: Single;
    }
    interface BhaaFooter {
        "query"?: Template.Query;
        "theme"?: Theme;
    }
    interface BhaaGridReveal {
    }
    interface BhaaHeader {
        "query"?: Template.Query;
        "theme"?: Theme;
    }
    interface BhaaHeartHerald {
        "theme"?: Theme;
    }
    interface BhaaLoadingSpinner {
    }
    interface BhaaMain {
        "query"?: Query<Single>;
        "slug"?: String;
    }
    interface BhaaMainSection {
    }
    interface BhaaMenu {
        "theme"?: Theme;
    }
    interface BhaaPage {
        "query"?: Query<Post>;
    }
    interface BhaaPost {
        "query"?: Query<Post>;
    }
    interface BhaaPostBreadcrumbs {
        "post"?: Single;
    }
    interface BhaaQzip {
    }
    interface BhaaSticker {
    }
    interface BhaaUpdates {
        "query"?: Query<Single>;
    }
    interface IntrinsicElements {
        "bhaa-404": Bhaa404;
        "bhaa-app": BhaaApp;
        "bhaa-expanding-copy": BhaaExpandingCopy;
        "bhaa-footer": BhaaFooter;
        "bhaa-grid-reveal": BhaaGridReveal;
        "bhaa-header": BhaaHeader;
        "bhaa-heart-herald": BhaaHeartHerald;
        "bhaa-loading-spinner": BhaaLoadingSpinner;
        "bhaa-main": BhaaMain;
        "bhaa-main-section": BhaaMainSection;
        "bhaa-menu": BhaaMenu;
        "bhaa-page": BhaaPage;
        "bhaa-post": BhaaPost;
        "bhaa-post-breadcrumbs": BhaaPostBreadcrumbs;
        "bhaa-qzip": BhaaQzip;
        "bhaa-sticker": BhaaSticker;
        "bhaa-updates": BhaaUpdates;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bhaa-404": LocalJSX.Bhaa404 & JSXBase.HTMLAttributes<HTMLBhaa404Element>;
            "bhaa-app": LocalJSX.BhaaApp & JSXBase.HTMLAttributes<HTMLBhaaAppElement>;
            "bhaa-expanding-copy": LocalJSX.BhaaExpandingCopy & JSXBase.HTMLAttributes<HTMLBhaaExpandingCopyElement>;
            "bhaa-footer": LocalJSX.BhaaFooter & JSXBase.HTMLAttributes<HTMLBhaaFooterElement>;
            "bhaa-grid-reveal": LocalJSX.BhaaGridReveal & JSXBase.HTMLAttributes<HTMLBhaaGridRevealElement>;
            "bhaa-header": LocalJSX.BhaaHeader & JSXBase.HTMLAttributes<HTMLBhaaHeaderElement>;
            "bhaa-heart-herald": LocalJSX.BhaaHeartHerald & JSXBase.HTMLAttributes<HTMLBhaaHeartHeraldElement>;
            "bhaa-loading-spinner": LocalJSX.BhaaLoadingSpinner & JSXBase.HTMLAttributes<HTMLBhaaLoadingSpinnerElement>;
            "bhaa-main": LocalJSX.BhaaMain & JSXBase.HTMLAttributes<HTMLBhaaMainElement>;
            "bhaa-main-section": LocalJSX.BhaaMainSection & JSXBase.HTMLAttributes<HTMLBhaaMainSectionElement>;
            "bhaa-menu": LocalJSX.BhaaMenu & JSXBase.HTMLAttributes<HTMLBhaaMenuElement>;
            "bhaa-page": LocalJSX.BhaaPage & JSXBase.HTMLAttributes<HTMLBhaaPageElement>;
            "bhaa-post": LocalJSX.BhaaPost & JSXBase.HTMLAttributes<HTMLBhaaPostElement>;
            "bhaa-post-breadcrumbs": LocalJSX.BhaaPostBreadcrumbs & JSXBase.HTMLAttributes<HTMLBhaaPostBreadcrumbsElement>;
            "bhaa-qzip": LocalJSX.BhaaQzip & JSXBase.HTMLAttributes<HTMLBhaaQzipElement>;
            "bhaa-sticker": LocalJSX.BhaaSticker & JSXBase.HTMLAttributes<HTMLBhaaStickerElement>;
            "bhaa-updates": LocalJSX.BhaaUpdates & JSXBase.HTMLAttributes<HTMLBhaaUpdatesElement>;
        }
    }
}
