/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Post, Query, TemplateQuery, Theme } from "@webpress/core";
export namespace Components {
    interface Bhaa404 {
    }
    interface BhaaExpandingCopy {
        "linkText": string;
        "post": Post;
    }
    interface BhaaFooter {
        "query": TemplateQuery;
        "theme": Theme;
    }
    interface BhaaFrontPage {
        "query": Query;
    }
    interface BhaaHeader {
        "query": TemplateQuery;
        "theme": Theme;
    }
    interface BhaaHeartHerald {
        "theme": Theme;
    }
    interface BhaaPage {
        "query": Query;
    }
    interface BhaaPost {
        "query": Query;
    }
    interface BhaaPostBreadcrumbs {
        "post": Post;
    }
    interface BhaaRoot {
        "query": TemplateQuery;
        "theme": Theme;
    }
    interface BhaaUpdates {
        "query": Query;
    }
    interface BhaaWrapper {
    }
}
declare global {
    interface HTMLBhaa404Element extends Components.Bhaa404, HTMLStencilElement {
    }
    var HTMLBhaa404Element: {
        prototype: HTMLBhaa404Element;
        new (): HTMLBhaa404Element;
    };
    interface HTMLBhaaExpandingCopyElement extends Components.BhaaExpandingCopy, HTMLStencilElement {
    }
    var HTMLBhaaExpandingCopyElement: {
        prototype: HTMLBhaaExpandingCopyElement;
        new (): HTMLBhaaExpandingCopyElement;
    };
    interface HTMLBhaaFooterElement extends Components.BhaaFooter, HTMLStencilElement {
    }
    var HTMLBhaaFooterElement: {
        prototype: HTMLBhaaFooterElement;
        new (): HTMLBhaaFooterElement;
    };
    interface HTMLBhaaFrontPageElement extends Components.BhaaFrontPage, HTMLStencilElement {
    }
    var HTMLBhaaFrontPageElement: {
        prototype: HTMLBhaaFrontPageElement;
        new (): HTMLBhaaFrontPageElement;
    };
    interface HTMLBhaaHeaderElement extends Components.BhaaHeader, HTMLStencilElement {
    }
    var HTMLBhaaHeaderElement: {
        prototype: HTMLBhaaHeaderElement;
        new (): HTMLBhaaHeaderElement;
    };
    interface HTMLBhaaHeartHeraldElement extends Components.BhaaHeartHerald, HTMLStencilElement {
    }
    var HTMLBhaaHeartHeraldElement: {
        prototype: HTMLBhaaHeartHeraldElement;
        new (): HTMLBhaaHeartHeraldElement;
    };
    interface HTMLBhaaPageElement extends Components.BhaaPage, HTMLStencilElement {
    }
    var HTMLBhaaPageElement: {
        prototype: HTMLBhaaPageElement;
        new (): HTMLBhaaPageElement;
    };
    interface HTMLBhaaPostElement extends Components.BhaaPost, HTMLStencilElement {
    }
    var HTMLBhaaPostElement: {
        prototype: HTMLBhaaPostElement;
        new (): HTMLBhaaPostElement;
    };
    interface HTMLBhaaPostBreadcrumbsElement extends Components.BhaaPostBreadcrumbs, HTMLStencilElement {
    }
    var HTMLBhaaPostBreadcrumbsElement: {
        prototype: HTMLBhaaPostBreadcrumbsElement;
        new (): HTMLBhaaPostBreadcrumbsElement;
    };
    interface HTMLBhaaRootElement extends Components.BhaaRoot, HTMLStencilElement {
    }
    var HTMLBhaaRootElement: {
        prototype: HTMLBhaaRootElement;
        new (): HTMLBhaaRootElement;
    };
    interface HTMLBhaaUpdatesElement extends Components.BhaaUpdates, HTMLStencilElement {
    }
    var HTMLBhaaUpdatesElement: {
        prototype: HTMLBhaaUpdatesElement;
        new (): HTMLBhaaUpdatesElement;
    };
    interface HTMLBhaaWrapperElement extends Components.BhaaWrapper, HTMLStencilElement {
    }
    var HTMLBhaaWrapperElement: {
        prototype: HTMLBhaaWrapperElement;
        new (): HTMLBhaaWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "bhaa-404": HTMLBhaa404Element;
        "bhaa-expanding-copy": HTMLBhaaExpandingCopyElement;
        "bhaa-footer": HTMLBhaaFooterElement;
        "bhaa-front-page": HTMLBhaaFrontPageElement;
        "bhaa-header": HTMLBhaaHeaderElement;
        "bhaa-heart-herald": HTMLBhaaHeartHeraldElement;
        "bhaa-page": HTMLBhaaPageElement;
        "bhaa-post": HTMLBhaaPostElement;
        "bhaa-post-breadcrumbs": HTMLBhaaPostBreadcrumbsElement;
        "bhaa-root": HTMLBhaaRootElement;
        "bhaa-updates": HTMLBhaaUpdatesElement;
        "bhaa-wrapper": HTMLBhaaWrapperElement;
    }
}
declare namespace LocalJSX {
    interface Bhaa404 {
    }
    interface BhaaExpandingCopy {
        "linkText"?: string;
        "post"?: Post;
    }
    interface BhaaFooter {
        "query"?: TemplateQuery;
        "theme"?: Theme;
    }
    interface BhaaFrontPage {
        "query"?: Query;
    }
    interface BhaaHeader {
        "query"?: TemplateQuery;
        "theme"?: Theme;
    }
    interface BhaaHeartHerald {
        "theme"?: Theme;
    }
    interface BhaaPage {
        "query"?: Query;
    }
    interface BhaaPost {
        "query"?: Query;
    }
    interface BhaaPostBreadcrumbs {
        "post"?: Post;
    }
    interface BhaaRoot {
        "query"?: TemplateQuery;
        "theme"?: Theme;
    }
    interface BhaaUpdates {
        "query"?: Query;
    }
    interface BhaaWrapper {
        "onBreakpointChanged"?: (event: CustomEvent<number>) => void;
    }
    interface IntrinsicElements {
        "bhaa-404": Bhaa404;
        "bhaa-expanding-copy": BhaaExpandingCopy;
        "bhaa-footer": BhaaFooter;
        "bhaa-front-page": BhaaFrontPage;
        "bhaa-header": BhaaHeader;
        "bhaa-heart-herald": BhaaHeartHerald;
        "bhaa-page": BhaaPage;
        "bhaa-post": BhaaPost;
        "bhaa-post-breadcrumbs": BhaaPostBreadcrumbs;
        "bhaa-root": BhaaRoot;
        "bhaa-updates": BhaaUpdates;
        "bhaa-wrapper": BhaaWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bhaa-404": LocalJSX.Bhaa404 & JSXBase.HTMLAttributes<HTMLBhaa404Element>;
            "bhaa-expanding-copy": LocalJSX.BhaaExpandingCopy & JSXBase.HTMLAttributes<HTMLBhaaExpandingCopyElement>;
            "bhaa-footer": LocalJSX.BhaaFooter & JSXBase.HTMLAttributes<HTMLBhaaFooterElement>;
            "bhaa-front-page": LocalJSX.BhaaFrontPage & JSXBase.HTMLAttributes<HTMLBhaaFrontPageElement>;
            "bhaa-header": LocalJSX.BhaaHeader & JSXBase.HTMLAttributes<HTMLBhaaHeaderElement>;
            "bhaa-heart-herald": LocalJSX.BhaaHeartHerald & JSXBase.HTMLAttributes<HTMLBhaaHeartHeraldElement>;
            "bhaa-page": LocalJSX.BhaaPage & JSXBase.HTMLAttributes<HTMLBhaaPageElement>;
            "bhaa-post": LocalJSX.BhaaPost & JSXBase.HTMLAttributes<HTMLBhaaPostElement>;
            "bhaa-post-breadcrumbs": LocalJSX.BhaaPostBreadcrumbs & JSXBase.HTMLAttributes<HTMLBhaaPostBreadcrumbsElement>;
            "bhaa-root": LocalJSX.BhaaRoot & JSXBase.HTMLAttributes<HTMLBhaaRootElement>;
            "bhaa-updates": LocalJSX.BhaaUpdates & JSXBase.HTMLAttributes<HTMLBhaaUpdatesElement>;
            "bhaa-wrapper": LocalJSX.BhaaWrapper & JSXBase.HTMLAttributes<HTMLBhaaWrapperElement>;
        }
    }
}
